OMS_NEW/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Data.OleDb;
using System.Linq;
using System.Web;
using System.Web.WebPages.Html;

namespace OMS_NEW.Models
{
    public class Employee
    {
        [Required(ErrorMessage = "Employee ID is Mandatory")]
        [Display(Name = "Employee ID")]
        public string ID { get; set; }

        [Required(ErrorMessage = "Employee Name is Mandatory")]
        [Display(Name = "Employee Name")]
        public string Name { get; set; }

        [RegularExpression(@"^([1-9]{1})([0-9]{9})$", ErrorMessage = "Enter a valid Mobile No.")]
        [Display(Name = "Mobile No")]
        public long MobileNo { get; set; }

        [Required(ErrorMessage = "Select Department")]
        [Display(Name = "Department Name")]
        public List<SelectListItem> Department { get; set; }

        [Required(ErrorMessage = "Select Company")]
        [Display(Name = "Company Name")]
        public List<SelectListItem> Company { get; set; }

        [Display(Name = "Select Circle")]
        public int Circle { get; set; }

        [Display(Name = "Select Division")]
        public int Division { get; set; }

        [Display(Name = "Select Sub-Division")]
        public int SubDivision { get; set; }

        [Display(Name = "Select Substation")]
        public int Substation { get; set; }

        [Required(ErrorMessage = "Select Complaint-Center")]
        [Display(Name = "Complaint-Center")]
        public int ComplaintCenter { get; set; }

        //public Employee()
        //{
        //    ID = "";
        //    Name = "";
        //    MobileNo = 1111111111;
        //    Department = new List<SelectListItem>();
        //    Department.Add(new SelectListItem() { Text = "Dept", Value = "ONM" });
        //    Company = new List<SelectListItem>();
        //    Company.Add(new SelectListItem() { Text = "Company1", Value = "BYPL" });
        //    ComplaintCenter = 1;
        //}

        public DataTable Emp_Dept_data()
        {
            try
            {
                Employee_registration reg = new Employee_registration();
                DataTable dt = reg.Emp_dept_data();
                return dt;
            }
            catch (OleDbException e)
            { throw e; }
        }
    }
}

OMS_NEW/Controllers/CmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMS_NEW.consumerdetails;
using OMS_NEW.gis_reference;
using OMS_NEW.Models;
using System.Data.OleDb;
using System.Data;
namespace OMS_NEW.Controllers
{
    public class CmsController : Controller
    {
        ISUService service = new ISUService();
        Service1 service1 = new Service1();
        static List<openNcc> _lstopenNcc = new List<openNcc>();
        static int faulttype;
        static string faultcat;
        List<string> company = new List<string>();
        List<string[,]> circle = new List<string[,]>();
        List<string[,]> division = new List<string[,]>();
        List<string[,]> subdivision = new List<string[,]>();
        static List<string> typefaulte;

        public List<string> FetchCompany()
        {
            DataSet ds = service1._1Get_Company();
            foreach (DataRow dt in ds.Tables[0].Rows)
            {
                company.Add(dt["Company"].ToString());
            }
            return company;
        }
        public List<string[,]> FetchCircle()
        {
            string[,] temper;
            DataSet ds = service1._2Get_Circle_list("");
            foreach (string temp in company)
            {
                foreach (DataRow dt in ds.Tables[0].Rows)
                {
                    if (temp == dt["Company"].ToString())
                    {
                        temper = new string[,] { { temp, dt["Circle"].ToString() } };
                        circle.Add(temper);

                    }
                }

            }
            return circle;
        }
        public List<string[,]> FetchDivision()
        {
            DataSet ds = service1._4Get_Division_list("");
            string[,] temper;
            foreach (string[,] temp in circle)
            {
                foreach (DataRow dt in ds.Tables[0].Rows)
                {
                    if (temp[0, 1] == dt["Circle"].ToString())
                    {
                        temper = new string[,] { { temp[0, 1], dt["DIVISION_N"].ToString() } };
                        division.Add(temper);

                    }
                }

            }
            return division;

        }
        public List<string[,]> FetchSubdivision()
        {
            DataSet ds = service1._6Get_Sub_Division_list("", "");
            string[,] temper;
            foreach (string[,] temp in division)
            {
                foreach (DataRow dt in ds.Tables[0].Rows)
                {
                    if (temp[0, 1] == dt["DIVISION_N"].ToString())
                    {
                        temper = new string[,] { { temp[0, 1], dt["SUBDIVISIO"].ToString() } };
                        subdivision.Add(temper);

                    }
                }

            }
            return subdivision;

        }
        public List<string[,]> FetchFaultCat()
        {
            string query = "select id,category from oms_fault_cat";
            string connection = System.Configuration.ConfigurationManager.ConnectionStrings["omscon"].ToString();
            OleDbConnection con = new OleDbConnection(connection);
            con.Open();
            OleDbCommand cmd = new OleDbCommand(query, con);
            cmd.ExecuteNonQuery();
            OleDbDataAdapter da = new OleDbDataAdapter(cmd);
            DataTable dt = new DataTable();
            da.Fill(dt);
            con.Close();
            string[,] temper;
            List<string[,]> faultcate = new List<string[,]>();
            foreach (DataRow dr in dt.Rows)
            {
                temper = new string[,] { { dr["ID"].ToString(), dr["CATEGORY"].ToString() } };
                faultcate.Add(temper);
            }



            return faultcate;
        }
        public List<string> Fetchtypefault(int ctg)
        {
            string query = "select type from oms_typeof_fault where category='" + ctg + "'";
            string connection = System.Configuration.ConfigurationManager.ConnectionStrings["omscon"].ToString();
            OleDbConnection con = new OleDbConnection(connection);
            con.Open();
            OleDbCommand cmd = new OleDbCommand(query, con);
            cmd.ExecuteNonQuery();
            OleDbDataAdapter da = new OleDbDataAdapter(cmd);
            DataTable dt = new DataTable();
            da.Fill(dt);
            con.Close();
            string temper;
            List<string> set = new List<string>();
            foreach (DataRow dr in dt.Rows)
            {
                set.Add(dr["TYPE"].ToString());
            }
            return set;
        }

        [HttpGet]
        public ActionResult home(int comtype = 0)
        {
            ModelState.Clear();
            cms cm = new cms();
            faulttype = comtype;
            cm.Date = DateTime.Now;
            List<string[,]> temp = FetchFaultCat();
            foreach (string[,] temper in temp)
            {
                if (faulttype == Int16.Parse(temper[0, 0]))
                {
                    faultcat = cm.faultcategory = temper[0, 1];
                    typefaulte = Fetchtypefault(faulttype);
                }
            }
            ViewData["typeoffault"] = new SelectList(typefaulte);
            return View(cm);
        }

        [HttpPost]
        [ActionName("home")]
        public ActionResult homepost(cms cm)
        {
            ModelState.Clear();
            cm.Date = DateTime.Now;
            cm.faultcategory = faultcat;
            ViewData["typeoffault"] = new SelectList(typefaulte);
            return View(cm);
        }

        [HttpPost]
        public ActionResult homedetails(cms cm)
        {
            ModelState.Clear();
            DataSet ds = new DataSet();
            cm.Date = DateTime.Now;
            if (cm.crn != null)
            {
                ds = service.Z_BAPI_CMS_ISU_CA_DISPLAY("", "", cm.crn, "", "", "");
            }
            if (cm.ca != null)
            {
                ds = service.Z_BAPI_CMS_ISU_CA_DISPLAY(cm.ca, "", "", "", "", "");
            }
            if (cm.contact1 != null)
            {
                ds = service.Z_BAPI_CMS_ISU_CA_DISPLAY("", "", "", cm.contact1, "", "");
            }

            if (ds.Tables[0].Rows.Count > 0)
            {
                cm.crn = ds.Tables[0].Rows[0]["Legacy_Acct"].ToString();
                cm.ca = ds.Tables[0].Rows[0]["Ca_Number"].ToString();
                cm.consumer_name = ds.Tables[0].Rows[0]["Bp_Name"].ToString();
                cm.contact1 = ds.Tables[0].Rows[0]["Telephone_No"].ToString();
                cm.address = ds.Tables[0].Rows[0]["House_Number"].ToString() + ds.Tables[0].Rows[0]["House_Number_Sup"].ToString() + ", " + ds.Tables[0].Rows[0]["Floor"].ToString() + ", " + ds.Tables[0].Rows[0]["Street"].ToString() + ", " + ds.Tables[0].Rows[0]["Street2"].ToString() + ", " + ds.Tables[0].Rows[0]["Street3"].ToString() + ", " + ds.Tables[0].Rows[0]["Street4"].ToString() + ", " + ds.Tables[0].Rows[0]["City"].ToString() + ", PostCode: " + ds.Tables[0].Rows[0]["Post_Code"].ToString() + " .";
            }
            cm.faultcategory = faultcat;
            ViewData["typeoffault"] = new SelectList(typefaulte);
            return View("home", cm);
        }


        [HttpPost]
        public ActionResult homesave(cms cm)
        {

            return View("home", cm);
        }


        [HttpPost]
        public ActionResult test(cms cm)
        {
            ModelState.Clear();
            cm.poleno = "jlm10542";
            return View(cm);
        }



        public ActionResult openNcc()
        {
            _lstopenNcc = GetopenNcc();
            return PartialView(_lstopenNcc);

        }
        private List<openNcc> GetopenNcc()
        {
            List<openNcc> _pvtList = new List<openNcc>();
            openNcc mod1 = new openNcc { EmpId = 1, EmployeeName = "Employee1", EmployeeDep = "EmployeeDep1" };
            openNcc mod2 = new openNcc { EmpId = 2, EmployeeName = "Employee2", EmployeeDep = "EmployeeDep2" };
            openNcc mod3 = new openNcc { EmpId = 3, EmployeeName = "Employee3", EmployeeDep = "EmployeeDep3" };
            openNcc mod4 = new openNcc { EmpId = 4, EmployeeName = "Employee4", EmployeeDep = "EmployeeDep4" };
            openNcc mod5 = new openNcc { EmpId = 5, EmployeeName = "Employee5", EmployeeDep = "EmployeeDep4" };
            openNcc mod6 = new openNcc { EmpId = 6, EmployeeName = "Employee6", EmployeeDep = "EmployeeDep4" };
            openNcc mod7 = new openNcc { EmpId = 7, EmployeeName = "Employee7", EmployeeDep = "EmployeeDep4" };
            openNcc mod8 = new openNcc { EmpId = 8, EmployeeName = "Employee8", EmployeeDep = "EmployeeDep4" };
            openNcc mod9 = new openNcc { EmpId = 6, EmployeeName = "Employee6", EmployeeDep = "EmployeeDep4" };
            openNcc mod10 = new openNcc { EmpId = 7, EmployeeName = "Employee7", EmployeeDep = "EmployeeDep4" };
            openNcc mod11 = new openNcc { EmpId = 8, EmployeeName = "Employee8", EmployeeDep = "EmployeeDep4" };
            _pvtList.Add(mod1);
            _pvtList.Add(mod2);
            _pvtList.Add(mod3);
            _pvtList.Add(mod4);
            _pvtList.Add(mod5);
            _pvtList.Add(mod6);
            _pvtList.Add(mod7);
            _pvtList.Add(mod8);
            _pvtList.Add(mod9);
            _pvtList.Add(mod10);
            _pvtList.Add(mod11);
            return _pvtList;
        }
        public ActionResult status()
        {
            _lstopenNcc = GetopenNcc();
            return View(_lstopenNcc);
        }



    }
}

OMS_NEW/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OMS_NEW.Models;
using System.Data;
using OMS_NEW.gis_reference;

namespace OMS_NEW.Controllers
{
    public class MainController : Controller
    {
        //
        // GET: /Main/

        [HttpGet]
        public ActionResult EmployeeRegistration()
        {
            try
            {
                Employee emp_reg = new Employee();
                DataTable dt = emp_reg.Emp_Dept_data();
                Service1 gis_service = new Service1();
                DataSet ds = new DataSet();
                ds = gis_service._1Get_Company();
                List<SelectListItem> Company = new List<SelectListItem>();
                for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                {
                    Company.Add(new SelectListItem()
                    {
                        Value = ds.Tables[0].Rows[i]["Company"].ToString(),
                        Text = ds.Tables[0].Rows[i]["Company"].ToString()
                    });
                }
                ViewData["Company"] = new SelectList(Company, "Value", "Text", "Select Company");

                List<SelectListItem> dept = new List<SelectListItem>();
                for (int i = 0; i < dt.Rows.Count; i++)
                {
                    dept.Add(new SelectListItem()
                    {
                        Text = dt.Rows[i]["DEPT_NAME"].ToString(),
                        Value = dt.Rows[i]["DEPT_ID"].ToString()
                    });
                }
                ViewData["Dept_name"] = new SelectList(dept, "Value", "Text", "Select Department");
            }
            catch
            { }
            return View();
        }

    }
}

OMS_NEW/Views/Home/Employee.cshtml
@{
    Layout = "~/Views/Shared/Emp_master.cshtml";
}

OMS_NEW/Views/Home/Employee_reg.cshtml
@model OMS_NEW.Models.Employee
@{
    Layout = "~/Views/Shared/Emp_master.cshtml";
}
<link href="~/Content/style.css" rel="stylesheet" />
<section id="loginForm">
    <h1>Employee Registration form</h1>
    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Registration Form</legend>
            <ol>
                <li>
                    @Html.LabelFor(m => m.ID)
                    @Html.TextBoxFor(m => m.ID)
                    @Html.ValidationMessageFor(m => m.ID).
                </li>
                <li>
                    @Html.LabelFor(m => m.Name)
                    @Html.TextBoxFor(m => m.Name)
                    @Html.ValidationMessageFor(m => m.Name)
                </li>
                <li>
                    @Html.LabelFor(m => m.Department)
                    @Html.DropDownListFor(m => m.Department, new SelectList(ViewBag.Dept_name, "Value", "Text"), "Select Department name", new { @id = "fcat" })
                    @Html.ValidationMessageFor(m => m.Department)
                </li>
                <li>
                    @Html.LabelFor(m => m.Company)
                    @Html.DropDownListFor(m => m.Company, new SelectList(ViewBag.Company, "Value", "Text"), "Select Company name", new { @id = "abc" })
                    @Html.ValidationMessageFor(m => m.Company)
                </li>
                <li>
                    @Html.LabelFor(m => m.Circle)
                    @Html.TextBoxFor(m => m.Circle)
                    @Html.ValidationMessageFor(m => m.Circle)
                </li>
                <li>
                    @Html.LabelFor(m => m.Division)
                    @Html.TextBoxFor(m => m.Division)
                    @Html.ValidationMessageFor(m => m.Division)
                </li>
                <li>
                    @Html.LabelFor(m => m.SubDivision)
                    @Html.TextBoxFor(m => m.SubDivision)
                    @Html.ValidationMessageFor(m => m.SubDivision)

                </li>
                <li>
                    @Html.LabelFor(m => m.Substation)
                    @Html.TextBoxFor(m => m.Substation)
                    @Html.ValidationMessageFor(m => m.Substation)
                </li>
                <li>
                    @Html.LabelFor(m => m.MobileNo)
                    @Html.TextBoxFor(m => m.MobileNo)
                    @Html.ValidationMessageFor(m => m.MobileNo)
                </li>
                <li>
                    @Html.LabelFor(m => m.ComplaintCenter)
                    @Html.TextBoxFor(m => m.ComplaintCenter)
                    @Html.ValidationMessageFor(m => m.ComplaintCenter)
                </li>
            </ol>
            <input type="submit" value="Register" />
        </fieldset>
    }
</section>

OMS_NEW/Views/Home/Index.cshtml
<html>
<head>
    <title>BSES Yamuna Power Limited</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <script src="~/JS/viewport.js"></script>
    <link href="~/Content/responsive.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" />

</head>
<body>

    <!-- Header -->
    <div id="header-wrapper">
        <header id="header" class="5grid">
            <div class="12u-first">

                <!-- Logo -->
                <h1><a href="#">
                    <img src="~/Content/Images/BSES_logo.png" /></a>
                </h1>
                <!-- Nav -->
                <nav>
                    @Html.ActionLink("Homepage", "Index")
                    @Html.ActionLink("User", "User", new { target = "_blank" })
                    @Html.ActionLink("Employee", "EmployeeRegistration","Main")
                    @Html.ActionLink("About", "About")
                    @Html.ActionLink("Contact", "Contact")
                </nav>

            </div>
        </header>
        <div id="banner">
            <div class="5grid 5grid-alt">
                <div class="6u-first">

                    <!-- Banner Copy -->
                    <p>The Outage Management System is an advanced computerized system which monitors and analyzes the whole process of fault restoration of power, from the receipt of consumer’s complaint & operation performed in the network to the normalization of supply including tracking of resources, in the power distribution and power supply system. This system gives an edge to BSES for providing quality and reliable services to its consumers.</p>
                </div>
                <div class="6u">

                    <!-- Banner Image -->
                    <a href="#" class="bordered-feature-image">
                        <img src="~/Images/banner.jpg" />
                    </a>

                </div>

                <div class="5grid-clear"></div>
            </div>
        </div>
    </div>

    <!-- Features -->
    <div id="features-wrapper">
        <div id="features">
            <div class="5grid">
                <div class="3u-first">

                    <!-- Feature #1 -->
                    <section>
                        <a href="#" class="bordered-feature-image">
                            <img src="~/Images/BSES.png" /></a>
                        <h2>Welcome to BSES in Delhi</h2>
                        <p>
                            The business of Delhi’s power distribution is effectively carried out by BRPL and BYPL which came into existence following the unbundling of Delhi Vidyut Board in July 2002 and caters to 32 lakh customers of two thirds of Delhi.							
                        </p>
                    </section>

                </div>
                <div class="3u">

                    <!-- Feature #2 -->
                    <section>
                        <a href="#" class="bordered-feature-image">
                            <img src="~/Images/Contact.png" />
                        </a>
                        <h2>Consumer Approach</h2>
                        <p>
                            BSES has come one step further of providing reliable and quality services to consumers by simplifying its consumer handling processes through interactive and integrated based approach.
                        </p>
                    </section>

                </div>
                <div class="3u">

                    <!-- Feature #3 -->
                    <section>
                        <a href="#" class="bordered-feature-image">
                            <img src="~/Images/BYPL.png" /></a>
                        <h2>Yamuna Power Limited</h2>
                        <p>
                            BYPL caters the power need of over 13.5 lakh customers spread over 200 sq. kms with a population density of 6750 per sq km of Central and East Delhi.
                        </p>
                    </section>

                </div>
                <div class="3u">

                    <!-- Feature #4 -->
                    <section>
                        <a href="#" class="bordered-feature-image">
                            <img src="~/Images/BRPL.png" /></a>
                        <h2>Rajdhani Power Limited</h2>
                        <p>
                            BRPL caters the power need of over 18.5 lakh customers spread over 750 sq. kms with a population density of 2465 per sq km of South and West Delhi.
                        </p>
                    </section>

                </div>
            </div>
        </div>
    </div>

    <!-- Content -->
    <div id="content-wrapper">
        <div id="content">
            <div class="5grid">
                <div class="4u-first">

                    <!-- Box #1 -->
                    <section>
                        <header>
                            <h2>How OMS Work</h2>
                            <h3>A subheading about how OMS work</h3>
                        </header>
                        <a href="#" class="feature-image">
                            <img src="~/Images/OMS.png" /></a>
                        <p>
                            OMS is an innovative computerized system which does the function of responding to the complaints of consumers.
                                        The system upon the criticality of the fault will be analyze from LT, HT & EHV levels and will be intimate
                                        the consumer about the approximate duration for its rectification.
                        </p>
                    </section>

                </div>
                <div class="4u">

                    <!-- Box #2 -->
                    <section>
                        <header>
                            <h2>Complain Registration Methods</h2>
                            <h3>A subheading about complain registration methods</h3>
                        </header>
                        <ul class="check-list">
                            <li>Via Short Message Service(SMS)</li>
                            <li>Via Interactive Voice Response System (IVRS)</li>
                            <li>From the OMS website</li>
                            <li>Phone call to Consumer Care Centre or Complaints Center </li>
                            <li>Personally visiting Complaint Centre</li>
                        </ul>
                    </section>

                </div>
                <div class="4u">

                    <!-- Box #3 -->
                    <section>
                        <header>
                            <h2>How to use Servies</h2>
                            <h3>And a final subheading about our clients</h3>
                        </header>
                        <ul class="quote-list">
                            <li>
                                <img src="~/Content/Images/sms.png" />
                                <p>
                                    Short Message Service(SMS)-:<br />
                                    NC to 5-61-61-08
                                </p>

                            </li>
                            <li>
                                <img src="~/Content/Images/IVRS.png" />
                                <p>Via Interactive Voice Response System (IVRS)-:<br />
                                    Dial 03999-9808</p>
                            </li>
                            <li>
                                <img src="~/Content/Images/OMS1.png" />
                                <p>From the OMS website-:<br />
                                    http://115.248.251.70/OMS</p>

                            </li>
                            <li>
                                <img src="~/Content/Images/call_center.png" />
                                <p>Phone call to Consumer Care Centre or direct Visting-:<br />
                                    http://115.248.251.70/OMS</p>

                            </li>

                        </ul>
                    </section>

                </div>
            </div>
        </div>
    </div>


    <!-- Copyright -->
    <div id="copyright">
        (c) 2012 Untitled Website. All rights reserved. Design by <a href="http://nodethirtythree.com/">nodethirtythree</a> + <a href="http://www.freecsstemplates.org/">FCT</a>. Images by <a href="http://fotogrph.com/">Fotogrph</a>.
    </div>

</body>
</html>

OMS_NEW/Views/Home/Login.cshtml
@model OMS_NEW.Models.LoginModel
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/Emp_master.cshtml";
}
<link href="~/Content/style.css" rel="stylesheet" />
<section id="loginForm">
<h1>Employee Login form</h1>
@using (Html.BeginForm("home", "Cms", FormMethod.Post, new { id = "comform" }))
{
    @Html.ValidationSummary(true)
        <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Emp_ID)
                @Html.TextBoxFor(m => m.Emp_ID)
                @Html.ValidationMessageFor(m => m.Emp_ID)
            </li>
            <li>
                @Html.LabelFor(m => m.Password)
                @Html.PasswordFor(m => m.Password)
                @Html.ValidationMessageFor(m => m.Password)
            </li>
        </ol>
            <a href="@Url.Action("home","Cms", new { comtype = 0 })">Log in</a>
    </fieldset>
}
      
</section>

OMS_NEW/Views/Home/Register.cshtml
@model OMS_NEW.Models.User_reg_Model
<link href="~/Content/style.css" rel="stylesheet" />
@{
    Layout = "~/Views/Shared/User_master.cshtml";
}
<section id="loginform">
<h1>User Mobile No registration form</h1>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Registration Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.CA_NO)
                @Html.TextBoxFor(m => m.CA_NO)
                @Html.ValidationMessageFor(m => m.CA_NO)
            </li>
            <li>
                @Html.LabelFor(m => m.Mob1)
                @Html.TextBoxFor(m => m.Mob1)
                @Html.ValidationMessageFor(m => m.Mob1)
            </li>
            <li>
                @Html.LabelFor(m => m.Mob2)
                @Html.TextBoxFor(m => m.Mob2)
                @Html.ValidationMessageFor(m => m.Mob2)
            </li>
             <li>
                @Html.LabelFor(m => m.Mob3)
                @Html.TextBoxFor(m => m.Mob3)
                @Html.ValidationMessageFor(m => m.Mob3)
            </li>
             <li>
                @Html.LabelFor(m => m.Mob4)
                @Html.TextBoxFor(m => m.Mob4)
                @Html.ValidationMessageFor(m => m.Mob4) 
            </li>
             <li>
                @Html.LabelFor(m => m.Mob5)
                @Html.TextBoxFor(m => m.Mob5)
                @Html.ValidationMessageFor(m => m.Mob5)
            </li>
        </ol>
        <input type="submit" value="Register" />
    </fieldset>
}
    </section>

OMS_NEW/Views/Home/Update_user_detail.cshtml
@using OMS_NEW.Controllers
@model OMS_NEW.Models.User_update_detail
@{
    Layout = "~/Views/Shared/Emp_master.cshtml";
}
<link href="~/Content/style.css" rel="stylesheet" />
<section id="loginform">
    <h3>User Mobile no updation form.</h3>
@using (Html.BeginForm("Update_user_detail", "Home", FormMethod.Post, new { id = "detail" }))
   {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Registraon Form</legend>
        <ol>
            <li>        
                @Html.LabelFor(m => m.Mob1)
                @Html.TextBoxFor(m=> m.Mob1)
                @Html.ValidationMessageFor(m => m.Mob1)
            </li>
            <li>
                @Html.LabelFor(m => m.Mob2)
                @Html.TextBoxFor(m => m.Mob2)
                @Html.ValidationMessageFor(m => m.Mob2)
            </li>
             <li>
                @Html.LabelFor(m => m.Mob3)
                @Html.TextBoxFor(m => m.Mob3)
                @Html.ValidationMessageFor(m => m.Mob3)
            </li>
             <li>
                @Html.LabelFor(m => m.Mob4)
                @Html.TextBoxFor(m => m.Mob4)
                @Html.ValidationMessageFor(m => m.Mob4)
            </li>
             <li>
                @Html.LabelFor(m => m.Mob5)
                @Html.TextBoxFor(m => m.Mob5)
                @Html.ValidationMessageFor(m => m.Mob5)
            </li>
            <li> @Html.TextBoxFor(m=> m.CA_NO,new { style = "display: none;" })</li>
        </ol>
        <input type="submit" name="Command" value="Update" />
    </fieldset>
   }
    </section>

OMS_NEW/Views/Home/User.cshtml
@{
    Layout = "~/Views/Shared/User_master.cshtml";
}

OMS_NEW/Views/Home/User_login.cshtml
@model OMS_NEW.Models.User_Login_form
@{
    ViewBag.Title = "Log in";
    Layout = "~/Views/Shared/User_master.cshtml";
    }
<link href="~/Content/style.css" rel="stylesheet" />
<section id="loginForm">
<h1>Use previously registered Mobile No for log in.</h1>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
        <fieldset>
        <legend>Log in Form</legend>
        <ol>
            <li>
                @Html.LabelFor(m => m.Mobile)
                @Html.TextBoxFor(m => m.Mobile)
                @Html.ValidationMessageFor(m => m.Mobile)
            </li>
        </ol>
        <input type="submit" value="Log in" />
    </fieldset>
}
</section>

OMS_NEW/Views/Home/User_retrive_data.cshtml
@using OMS_NEW.Controllers
@model OMS_NEW.Models.User_update_detail
@{
    Layout = "~/Views/Shared/User_master.cshtml";
}
<link href="~/Content/style.css" rel="stylesheet" />
<section id="loginform">
<h1>Enter CA Number for Mobile number updation </h1>
@using (Html.BeginForm("User_retrive_data", "Home", FormMethod.Post, new { id = "detail" }))
   {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Registraon Form</legend>
        <ol>
            <li>                                                                                                
                @Html.LabelFor(m => m.CA_NO)
                @Html.TextBoxFor(m => m.CA_NO)
                @Html.ValidationMessageFor(m => m.CA_NO)
          </li>
        </ol>
        <input type="submit" name="Command" value="Get Detail" />
    </fieldset>
   }
    </section>